[package]
name = "unix-signal"
version = "0.1.1"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "Unix signals"
license = "MIT OR Apache-2.0"

[dependencies]
flags = "0.1.1"
libc = { version = "0.2", default-features = false }
syscall = "0.2"
unix = "0.6"
